src/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import never_cache
from django.views.static import serve

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('product/', include('product.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, view=never_cache(serve))

src/product/urls.py
from django.urls import path
from django.views.generic import TemplateView

from product.views.product import CreateProductView, ProductListView, ProductSearchView, EditProductView
from product.views.variant import VariantView, VariantCreateView, VariantEditView

app_name = "product"

urlpatterns = [
    # Variants URLs
    path('variants/', VariantView.as_view(), name='variants'),
    path('variant/create', VariantCreateView.as_view(), name='create.variant'),
    path('variant/<int:id>/edit', VariantEditView.as_view(), name='update.variant'),

    # Products URLs
    path('create/', CreateProductView.as_view(), name='create.product'),
    path('list/', ProductListView.as_view(), name='list.product'),
    path('search/', ProductSearchView.as_view(), name='searched'),
    path('<int:id>/edit', EditProductView.as_view(), name='update'),
]

src/product/models.py
from django.db import models
import datetime

# Create your models here.
class Variant(models.Model):
    title = models.CharField(max_length=40)
    color = models.CharField(max_length=20, default=None)
    size = models.CharField(max_length=10, default=None)
    description = models.TextField()
    active = models.BooleanField(default=True)
    def __str__(self) -> str:
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=255)
    sku = models.SlugField(max_length=255)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def get_date(self):
        time = datetime.datetime.now()
        if self.created_at.day == time.day:
            return str(time.hour - self.created_at.hour) + " hours ago"
        else:
            if self.created_at.month == time.month:
                return str(time.day - self.created_at.day) + " days ago"
            else:
                if self.created_at.year == time.year:
                    return str(time.month - self.created_at.month) + " months ago"
        return self.created_at

    def __str__(self) -> str:
        return self.title



class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    file_path = models.URLField()


class ProductVariant(models.Model):
    variant_title = models.CharField(max_length=255)
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.variant_title

class ProductVariantPrice(models.Model):
    product_variant_one = models.ForeignKey(ProductVariant, on_delete=models.CASCADE,
                                            related_name='product_variant_one')
    product_variant_two = models.ForeignKey(ProductVariant, on_delete=models.CASCADE,
                                            related_name='product_variant_two')
    product_variant_three = models.ForeignKey(ProductVariant, on_delete=models.CASCADE,
                                              related_name='product_variant_three')
    variant_one_price = models.FloatField(default=0)
    variant_two_price = models.FloatField(default=0)
    variant_three_price = models.FloatField(default=0)
    variant_one_stock = models.FloatField(default=0)
    variant_two_stock = models.FloatField(default=0)
    variant_three_stock = models.FloatField(default=0)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

src/product/forms.py
from django.db.models import fields
from django.forms import forms, ModelForm, CharField, TextInput, Textarea, BooleanField, CheckboxInput, IntegerField
from django.forms.widgets import NumberInput

from product.models import ProductVariantPrice, Variant, Product


class VariantForm(ModelForm):
    class Meta:
        model = Variant
        fields = '__all__'
        widgets = {
            'title': TextInput(attrs={'class': 'form-control'}),
            'description': Textarea(attrs={'class': 'form-control'}),
            'active': CheckboxInput(attrs={'class': 'form-check-input', 'id': 'active'})
        }

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        widgets = {
            'title': TextInput(attrs={'class': 'form-control'}),
            'sku': TextInput(attrs={'class': 'form-control'}),
            'description': Textarea(attrs={'class': 'form-control'}),
        }

class ProductEditForm(forms.Form):
    title = CharField(max_length=100, widget=TextInput(attrs={'class': 'form-control'}))
    sku = CharField(max_length = 100, widget=TextInput(attrs={'class': 'form-control'}))
    description = CharField(widget=Textarea(attrs={'class': 'form-control'}))
    variant_one_price = IntegerField()
    variant_two_price = IntegerField()
    variant_three_price = IntegerField()
    variant_one_stock = IntegerField()
    variant_two_stock = IntegerField()
    variant_three_stock = IntegerField()

    def save(self):
        cleaned_data = self.cleaned_data
        # product = super(ProductEditForm, self).save(commit=False)
        # product.save()
        # return product
        

class ProductVariantPriceForm(ModelForm):
    class Meta:
        model = ProductVariantPrice
        fields = '__all__'
        widgets = {
            'variant_one_price': NumberInput(attrs={'class': 'form-control'}),
            'variant_two_price': NumberInput(attrs={'class': 'form-control'}),
            'variant_three_price': NumberInput(attrs={'class': 'form-control'}),
            'variant_one_stock': NumberInput(attrs={'class': 'form-control'}),
            'variant_two_stock': NumberInput(attrs={'class': 'form-control'}),
            'variant_three_stock': NumberInput(attrs={'class': 'form-control'}),
        }

src/product/views/product.py
from django.views import generic, View
from product.models import ProductVariant, ProductVariantPrice, Variant, Product
from django.views.generic import ListView
from django.views.generic.edit import FormView, UpdateView
from product.forms import ProductEditForm, VariantForm, ProductVariantPriceForm
from django.core.paginator import Paginator
from django.shortcuts import render
from django.urls import reverse_lazy
from django.db.models import Q
import datetime
from django.http import HttpResponseRedirect

class CreateProductView(generic.TemplateView):
    template_name = 'products/create.html'

    def get_context_data(self, **kwargs):
        context = super(CreateProductView, self).get_context_data(**kwargs)
        variants = Variant.objects.filter(active=True).values('id', 'title')
        context['product'] = True
        context['variants'] = list(variants.all())
        return context

class ProductListView(ListView):
    model = Product
    template_name = 'products/list.html'
    paginate_by = 3
    queryset = Product.objects.all()
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context['product_variants'] = ProductVariantPrice.objects.all()
        context['variants'] = Variant.objects.all()
        return context



class ProductSearchView(ListView):
    template_name = 'products/filter.html'
    paginate_by = 2

    def get_queryset(self):
        title = self.request.GET.get('title')
        variant = self.request.GET.get('variant')
        range_from = self.request.GET.get('price_from')
        range_to = self.request.GET.get('price_to')
        date = self.request.GET.get('date')

        search_results = Product.objects.filter(
            Q(title__icontains=title)
        )
        if date:
            date = datetime.datetime.strptime(date, '%Y-%m-%d').date()
            search_date = Product.objects.filter(created_at__lte=date)
            search_results = search_results | search_date


        if variant != None:
            variant_search_query = Product.objects.filter(
                (
                    Q(productvariant__variant__color=variant) |
                    Q(productvariant__variant__size=variant)
                )
            )
            search_results = search_results & variant_search_query
        if not range_from and not range_to:
            range_from=0
            range_to=100000
        search_obj = ProductVariantPrice.objects.filter(product__in=search_results)

        pricing_search_results = ProductVariantPrice.objects.filter(
            Q(variant_one_price__range=[range_from, range_to]) |
            Q(variant_two_price__range=[range_from, range_to]) |
            Q(variant_three_price__range=[range_from, range_to])
        )
        new_search_results = search_obj & pricing_search_results

        return new_search_results

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        product_var = Variant.objects.all()
        product_var_price = ProductVariantPrice.objects.all()
        context['variants'] = product_var
        context['product_variant_price'] = product_var_price
        return context

class EditProductView(FormView):
    pk_url_kwarg = 'id'
    template_name = 'products/edit.html'
    form_class = ProductEditForm
    success_url = reverse_lazy('product:list.product')

    def get_initial(self):
        initial = super().get_initial()
        id = self.kwargs.get('id')
        product = Product.objects.filter(id = id)
        initial['title'] = product[0].title
        initial['sku'] = product[0].sku
        initial['description'] = product[0].description
        product_variant_price = ProductVariantPrice.objects.filter(product__id = id)
        initial['variant_one_price'] = product_variant_price[0].variant_one_price
        initial['variant_two_price'] = product_variant_price[0].variant_two_price
        initial['variant_three_price'] = product_variant_price[0].variant_three_price
        initial['variant_one_stock'] = product_variant_price[0].variant_one_stock
        initial['variant_two_stock'] = product_variant_price[0].variant_two_stock
        initial['variant_three_stock'] = product_variant_price[0].variant_three_stock
        
        return initial

    def form_valid(self, form):
        title = form.cleaned_data['title']
        # product, _ = Product.objects.get_or_create(title = title)
        # product.save()
        form.save()
        return super(EditProductView, self).form_valid(form)
    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        return HttpResponseRedirect(self.success_url)


# class EditProductView(UpdateView):
#     pk_url_kwarg = 'id'
#     model = ProductVariantPrice
#     second_model = Product
#     template_name = 'products/edit.html'
#     form_class = ProductVariantPriceForm
#     second_form_class = ProductEditForm
#     success_url = reverse_lazy('product:list.product')

#     def get_context_data(self, **kwargs):
#         context = super(EditProductView, self).get_context_data(**kwargs)
#         context['product'] = True
#         if 'form' not in context:
#             context['form'] = self.form_class(self.request.GET)
#         if 'form2' not in context:
#             context['form2'] = self.second_form_class(self.request.GET)
#         context['product'] = True
#         return context










        




    

src/product/views/variant.py
from django.views import generic
from django.views.generic import ListView, CreateView, UpdateView

from product.forms import VariantForm
from product.models import Variant


class BaseVariantView(generic.View):
    form_class = VariantForm
    model = Variant
    template_name = 'variants/create.html'
    success_url = '/product/variants'


class VariantView(BaseVariantView, ListView):
    template_name = 'variants/list.html'
    paginate_by = 10

    def get_queryset(self):
        filter_string = {}
        print(self.request.GET)
        for key in self.request.GET:
            if self.request.GET.get(key):
                filter_string[key] = self.request.GET.get(key)
        return Variant.objects.filter(**filter_string)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = True
        context['request'] = ''
        if self.request.GET:
            context['request'] = self.request.GET['title__icontains']
        return context


class VariantCreateView(BaseVariantView, CreateView):
    pass


class VariantEditView(BaseVariantView, UpdateView):
    pk_url_kwarg = 'id'

src/product/templates/products/create.html
{% extends 'backend/base.html' %}

{% block title %} Create Product {% endblock %}

{% block content %}
<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Create Product</h1>
    <a href="{% url 'product:create.product' %}" class="float-right btn btn-primary">All Product</a>
</div>

<div id="app">
    <create-product :variants="{{variants|safe}}"></create-product>
</div>

{% endblock %}

src/product/templates/products/edit.html
{% extends 'backend/base.html' %}

{% block title %} Product List {% endblock %}

{% block content %}

    {% if user.is_authenticated %}
    <h3>Edit Product</h3>
        <form method = "POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-success">Update</button> <br>

        </form>
    {% endif %}
{% endblock %}

src/product/templates/products/filter.html
{% extends 'backend/base.html' %}

{% block title %} Product List {% endblock %}

{% block content %}



<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Products</h1>
</div>


<div class="card">
    <form action="{% url 'product:searched' %}" method="get" class="card-header">
        {% csrf_token %}
        <div class="form-row justify-content-between">
            <div class="col-md-2">
                <input type="text" name="title" placeholder="Product Title" class="form-control">
            </div>
            <div class="col-md-2">
                
                <select name="variant" id="" class="form-control">
                    <option selected disabled>--Select A Variant--</option>
                    {% for variant in variants %}
                            <option>{{ variant.color }}</option>

                    {% endfor %}
                    {% for variant in variants %}

                            <option>{{ variant.size }}</option>
                    {% endfor %}
                </select>
                
            </div>

            <div class="col-md-3">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Price Range</span>
                    </div>
                    <input type="text" name="price_from" aria-label="First name" placeholder="From"
                           class="form-control">
                    <input type="text" name="price_to" aria-label="Last name" placeholder="To" class="form-control">
                </div>
            </div>
            <div class="col-md-2">
                <input type="date" name="date" placeholder="Date" class="form-control">
            </div>
            <div class="col-md-1">
                <button type="submit" class="btn btn-primary float-right"><i class="fa fa-search"></i></button>
            </div>
        </div>
    </form>

    <div class="card-body">
        <div class="table-response">
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Variant</th>
                    <th width="150px">Action</th>
                </tr>
                </thead>

                <tbody>
                    {% if object_list %}
                    {% for item in object_list %}
                <tr>
                    <td>{{ item.product.id }}</td>
                    <td>{{ item.product.title }} <br> Created {{ item.product.get_date }}</td>
                    <td>{{ item.product.description }}</td>
                    <td>
                        
                        <dl class="row mb-0" style="height: 80px; overflow: hidden" id="variant">
                            {% for variant in product_variant_price %}
                                {% if variant.product.title == item.product.title %}
                            <dt class="col-sm-3 pb-0">
                                {{ variant.product_variant_one.variant.color }}/{{variant.product_variant_one.variant.size }}<br>
                                {{ variant.product_variant_two.variant.color }}/{{variant.product_variant_two.variant.size }}<br>
                                {{ variant.product_variant_three.variant.color }}/{{variant.product_variant_three.variant.size }}<br>
                            </dt>
                            <dd class="col-sm-9">
                                <dl class="row mb-0">
                                    <dt class="col-sm-4 pb-0">{{variant.variant_one_price}}</dt>
                                    <dd class="col-sm-8 pb-0">{{variant.variant_one_stock}}</dd><br>
                                    <dt class="col-sm-4 pb-0">{{variant.variant_two_price}}</dt>
                                    <dd class="col-sm-8 pb-0">{{variant.variant_two_stock}}</dd><br>
                                    <dt class="col-sm-4 pb-0">{{variant.variant_three_price}}</dt>
                                    <dd class="col-sm-8 pb-0">{{variant.variant_three_stock}}</dd>
                                </dl>
                            </dd>
                            {% else %}
                            {% endif %}
                        {% endfor %}
                        </dl>

                        <button onclick="$('#variant').toggleClass('h-auto')" class="btn btn-sm btn-link">Show more
                        </button>
                    </td>
                    <td>
                        <div class="btn-group btn-group-sm">
                            <a href="{% url 'product:update' item.product.id %}" class="btn btn-success">Edit</a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
                {% endif %}
                </tbody>

            </table>
        </div>

    </div>
    
    <div class="ml-auto" >
        <div>
            {% if object_list.count > 0 %}
            <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>
        {% endif %}
        </div>
        <nav aria-label="Page navigation">   <ul class="pagination">
            {% if page_obj.has_previous %}
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
                </a>
                {% endif %}
            
            {% for n in page_obj.paginator.page_range %}
              {% if page_obj.number == n %}
                <li class="page-item active">
                  <span class="page-link">{{ n }}<span class="sr-only">(current)</span></span>
                </li>
              {% elif n > page_obj.number|add:'-3' and n < page_obj.number|add:'3' %}
                <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
              {% endif %}
            {% endfor %}
            
            {% if page_obj.has_next %}
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
                </a>
                {% endif %}   
            </ul> 
        </nav>
    </div>
    <div class="card-footer">
        <div class="row justify-content-between">
            <div class="col-md-6">
                {% if object_list %}
                    <p>Showing {{ page_obj.start_index }} to {{ page_obj.end_index }} out of {{ page_obj.paginator.count }}</p>
                {% endif %}
            </div>
            <div class="col-md-2">

            </div>
        </div>
    </div>
</div>
{% endblock %}

src/product/templates/products/list.html
{% extends 'backend/base.html' %}

{% block title %} Product List {% endblock %}

{% block content %}




<div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">Products</h1>
</div>


<div class="card">
    <form action="{% url 'product:searched' %}" method="get" class="card-header">
        {% csrf_token %}
        <div class="form-row justify-content-between">
            <div class="col-md-2">
                <input type="text" name="title" placeholder="Product Title" class="form-control">
            </div>
            <div class="col-md-2">
                <select name="variant" id="" class="form-control">
                    <option selected disabled>--Select A Variant--</option>
                    {% for variant in variants %}
                            <option>{{ variant.color }}</option>

                    {% endfor %}
                    {% for variant in variants %}

                            <option>{{ variant.size }}</option>
                    {% endfor %}
                </select>

            </div>

            <div class="col-md-3">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">Price Range</span>
                    </div>
                    <input type="text" name="price_from" aria-label="First name" placeholder="From"
                           class="form-control">
                    <input type="text" name="price_to" aria-label="Last name" placeholder="To" class="form-control">
                </div>
            </div>
            <div class="col-md-2">
                <input type="date" name="date" placeholder="Date" class="form-control">
            </div>
            <div class="col-md-1">
                <button type="submit" class="btn btn-primary float-right"><i class="fa fa-search"></i></button>
            </div>
        </div>
    </form>

    <div class="card-body">
        <div class="table-response">
            <table class="table">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Variant</th>
                    <th width="150px">Action</th>
                </tr>
                </thead>

                <tbody>
                    {% if products %}
                    {% for item in products %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.title }} <br> Created {{ item.get_date }}</td>
                    <td>{{ item.description }}</td>
                    <td>
                        <dl class="row mb-0" style="height: 80px; overflow: hidden" id="variant">
                            {% for variant in product_variants %}
                                {% if variant.product.title == item.title %}
                            <dt class="col-sm-3 pb-0">
                                {{ variant.product_variant_one.variant.color }}/{{variant.product_variant_one.variant.size }}<br>
                                {{ variant.product_variant_two.variant.color }}/{{variant.product_variant_two.variant.size }}<br>
                                {{ variant.product_variant_three.variant.color }}/{{variant.product_variant_three.variant.size }}<br>
                            </dt>
                            <dd class="col-sm-9">
                                <dl class="row mb-0">
                                    <dt class="col-sm-4 pb-0">{{variant.variant_one_price}}</dt>
                                    <dd class="col-sm-8 pb-0">{{variant.variant_one_stock}}</dd><br>
                                    <dt class="col-sm-4 pb-0">{{variant.variant_two_price}}</dt>
                                    <dd class="col-sm-8 pb-0">{{variant.variant_two_stock}}</dd><br>
                                    <dt class="col-sm-4 pb-0">{{variant.variant_three_price}}</dt>
                                    <dd class="col-sm-8 pb-0">{{variant.variant_three_stock}}</dd>
                                </dl>
                            </dd>
                            {% else %}
                            {% endif %}
                        {% endfor %}
                        </dl>

                        <button onclick="$('#variant').toggleClass('h-auto')" class="btn btn-sm btn-link">Show more
                        </button>
                    </td>
                    <td>
                        <div class="btn-group btn-group-sm">
                            <a href="{% url 'product:update' item.id %}" class="btn btn-success">Edit</a>
                        </div>
                    </td>
                </tr>
                {% endfor %}
                {% endif %}
                </tbody>

            </table>
        </div>

    </div>
    <div class="ml-auto" >
        <div>
            {% if object_list.count > 0 %}
            <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </span>
        {% endif %}
        </div>
        <nav aria-label="Page navigation">   <ul class="pagination">
            {% if page_obj.has_previous %}
                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                <span class="sr-only">Previous</span>
                </a>
                {% endif %}
            
            {% for n in page_obj.paginator.page_range %}
              {% if page_obj.number == n %}
                <li class="page-item active">
                  <span class="page-link">{{ n }}<span class="sr-only">(current)</span></span>
                </li>
              {% elif n > page_obj.number|add:'-3' and n < page_obj.number|add:'3' %}
                <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
              {% endif %}
            {% endfor %}
            
            {% if page_obj.has_next %}
                <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                <span class="sr-only">Next</span>
                </a>
                {% endif %}   
            </ul> 
        </nav>
    </div>
    <div class="card-footer">
        <div class="row justify-content-between">
            <div class="col-md-6">
                {% if object_list %}
                    <p>Showing {{ page_obj.start_index }} to {{ page_obj.end_index }} out of {{ page_obj.paginator.count }}</p>
                {% endif %}
            </div>
            <div class="col-md-2">

            </div>
        </div>
    </div>
</div>
{% endblock %}